[environment]
active = 2
# 0: development
# 1: production
# 2: docker
port = 8082

[db]
dbname = "eventstore"
docname = "events"

# file paths for logging and some error messages remain in logger.go 
# to avoid circular dependencies between logging and configuration

[development]
    [development.database]
    host = "localhost"
    port = "27017"
[docker]
    [docker.database]
    host = "audit-server"
    port = "27017"

[urls]
api = "/api"
system-event = "/systemevent"
user-command = "/usercommand"
quote-server = "/quoteserver"
error-event = "/errorevent"
account-transaction = "/accounttransaction"
log-all = "/log"
log = "/log/:userName"

######################
# maps
######################

[[event-map]]
num = 0
event-type = "usercommand"

[[event-map]]
num = 1
event-type = "systemevent"

[[event-map]]
num = 2
event-type = "errorevent"

[[event-map]]
num = 3
event-type = "quoteserver"

[[event-map]]
num = 4
event-type = "accounttransaction"

[[env-map]]
index = 0
type = "development"

[[env-map]]
index = 1
type = "production"

[[env-map]]
index = 2
type = "docker"

