[environment]
active = 1
# 1: development
# 2: production

[db]
dbname = "eventstore"
docname = "events"

[logger]
tracefilepath = "trace.log"
infofilepath = "info.log"
warningfilepath = "warning.log"
errorfilepath = "error.log"
logfilepath = "1UserLogFile.xml"

[development]
    [development.database]
    url = "localhost:27017"


[messages]
