[environment]
active = 1
# 1: development
# 2: production
port = 8082

[db]
dbname = "eventstore"
docname = "events"

# file paths for logging and some error messages remain in logger.go 
# to avoid circular dependencies between logging and configuration

[development]
    [development.database]
    host = "localhost"
    port = "27017"

[urls]
api = "/api"
system-event = "/systemevent"
user-command = "/usercommand"
quote-server = "/quoteserver"
error-event = "/errorevent"
account-transaction = "/accounttransaction"
log-all = "/log"
log = "/log/:userName"
